### ISSUE TITLE
Request: FIM-43 and Blowpipe

### ISSUE THREAD

**Issue by Xeno426** [Des-mundo/LowDigitsMANPADS#1]
Couldn't find a thread on the DCS forums for this, so I figured I'd place this here.

I'd like to see the FIM-43C and Blowpipe. I have some simple files for that purpose, but they're rather slapdash. I have found that the Sea Cat code provides a suitably "wobbly" flight profile for the Blowpipe, and in my testing it almost never hits anything.

I can share the files I have if you're interested.

**Comment by Des-mundo** [comment]
Added by Xeno426
